name: minio_dd
description: A new Flutter package with minio.
version: 0.0.2
homepage: https://github.com/duanchanghe/minio_dd.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  meta: '>=1.0.0 <2.0.0'
  http: '>=0.0.1 <1.0.0'
  crypto: '>=3.0.0 <4.0.0'
  convert: '>=2.0.0 <3.0.0'
  xml: '>=4.0.0 <5.0.0'
  buffer: '>=1.0.0 <2.0.0'
  intl: '>=0.0.1 <1.0.0'
  mime: '>=0.0.1 <1.0.0'
  path: '>=1.0.0 <2.0.0'

dev_dependencies:
  pedantic: '>=1.0.0 <2.0.0'
  test: '>=1.0.0 <2.0.0'
  html: '>=0.0.1 <1.0.0'
