name: minio_dd
description: A new Flutter package with minio.
version: 0.0.1
homepage: https://github.com/duanchanghe/minio_dd.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  crypto: ^3.0.0
  convert: ^3.0.0
  xml: ^5.0.2
  buffer: ^1.0.7
  intl: ^0.17.0
  mime: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.16.8
  html: ^0.15.0
